export const dasaUnidades = [
  { unidade: "PRAIME", marca: "CERPE" },
  { unidade: "João de Barros", marca: "CERPE" },
  { unidade: "Canela", marca: "NTO - Bahia" },
  { unidade: "ALDEOTA", marca: "LabPasteur" },
  { unidade: "VILA DO ATLANTICO", marca: "IMAGE" },
  { unidade: "CERPE GRAÇAS - HOSPITAL", marca: "CERPE" },
  { unidade: "JAIME DA FONTE", marca: "CERPE" },
  { unidade: "NTO-NORDESTE", marca: "CERPE" },
  { unidade: "BOA VIAGEM I", marca: "CERPE" },
  { unidade: "BOA VIAGEM II", marca: "CERPE" },
  { unidade: "IBURA", marca: "CERPE" },
  { unidade: "ABDIAS", marca: "CERPE" },
  { unidade: "Abreu Lima", marca: "CERPE" },
  { unidade: "DERBY 2", marca: "CERPE" },
  { unidade: "IPSEP", marca: "CERPE" },
  { unidade: "PIEDADE II", marca: "CERPE" },
  { unidade: "GOIANA", marca: "CERPE" },
  { unidade: "CASA CAIADA", marca: "CERPE" },
  { unidade: "IPOJUCA", marca: "CERPE" },
  { unidade: "PALMARES", marca: "CERPE" },
  { unidade: "RIBEIRÃO", marca: "CERPE" },
  { unidade: "SURUBIM", marca: "CERPE" },
  { unidade: "OLINDA", marca: "CERPE" },
  { unidade: "PAULISTA 2", marca: "CERPE" },
  { unidade: "IBURA II", marca: "GILSON CIDRIN" },
  { unidade: "SETUBAL", marca: "CERPE" },
  { unidade: "GRAVATÁ", marca: "CERPE" },
  { unidade: "BOA VIAGEM", marca: "BORIS BERNSTEIN" },
  { unidade: "PIEDADE", marca: "BORIS BERNSTEIN" },
  { unidade: "MESSEJANA", marca: "LabPasteur" },
  { unidade: "BEZERRA DE MENEZES", marca: "LabPasteur" },
  { unidade: "PARANGABA", marca: "LabPasteur" },
  { unidade: "FATIMA", marca: "LabPasteur" },
  { unidade: "OLIVEIRA PAIVA", marca: "LabPasteur" },
  { unidade: "RENASCENÇA", marca: "GASPAR" },
  { unidade: "ANJO DA GUARDA", marca: "GASPAR" },
  { unidade: "CALHAU", marca: "GASPAR" },
  { unidade: "KIDS - HOLANDÊSES", marca: "GASPAR" },
  { unidade: "ITAGUARA", marca: "IMAGE MEMORIAL" },
  { unidade: "Campo Grande", marca: "IMAGE MEMORIAL" },
  { unidade: "LE-SÃO MARCOS", marca: "LEME" },
  { unidade: "CANELA II", marca: "LEME" },
  { unidade: "GARIBALDI", marca: "LEME" },
  { unidade: "PATAMARES", marca: "LEME" },
  { unidade: "CABULA", marca: "LEME" },
  { unidade: "IMBUI", marca: "LEME" },
  { unidade: "NTO-ADM", marca: "LEME" },
  { unidade: "ITAIGARA", marca: "LEME" },
  { unidade: "VILA DO ATLANTICO II", marca: "LEME" },
  { unidade: "MEMORIAL", marca: "IMAGE" },
  { unidade: "DERBY", marca: "CERPE" },
  { unidade: "CAXANGÁ", marca: "CERPE" },
  { unidade: "MADALENA - PRIME", marca: "CERPE - PRAIME" },
  { unidade: "OLINDA II", marca: "BORIS BERNSTEIN" },
  { unidade: "PAULISTA", marca: "BORIS BERNSTEIN" },
  { unidade: "BEBERIBE", marca: "CERPE" },
  { unidade: "GRAÇAS", marca: "CERPE" },
  { unidade: "GRAVATÁ II", marca: "CERPE" },
  { unidade: "IGARASSU", marca: "CERPE" },
  { unidade: "CE NTH RECIFE", marca: "CERPE" },
  { unidade: "JABOATÃO", marca: "CERPE" },
  { unidade: "JANGA", marca: "CERPE" },
  { unidade: "PRAZERES", marca: "CERPE" },
  { unidade: "SETUBAL II", marca: "CERPE" },
  { unidade: "IMBIRIBEIRA", marca: "NTO - Recife" },
  { unidade: "JARDIM SÃO PAULO", marca: "CERPE" },
  { unidade: "HOLANDESES", marca: "GASPAR" },
  { unidade: "JP GASPAR", marca: "GASPAR" },
  { unidade: "LEME", marca: "IMAGE" },
  { unidade: "ARMAZÉM", marca: "LABPASTEUR" },
  { unidade: "ITAPOÃ", marca: "LEME" },
  { unidade: "SÃO MARCOS", marca: "LEME" },
  { unidade: "ONDINA", marca: "NTO - Recife" },
  { unidade: "STELLA MARIS", marca: "LEME" },
  { unidade: "CABO DE SANTO AGOSTINHO", marca: "BORIS BERNSTEIN" },
  { unidade: "JARDINS", marca: "GASPAR" },
  { unidade: "CAMINHO DE AREIA", marca: "LEME" },
  { unidade: "COSTA AZUL", marca: "LEME" },
  { unidade: "CAMINHO DAS ÁRVORES", marca: "LEME" }
];
