import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        {/* TESTE GLOBAL */}
        <div
          style={{
            background: "red",
            color: "white",
            padding: "15px",
            textAlign: "center",
            fontWeight: "bold",
            fontSize: "18px"
          }}
        >
          🚨 TESTE GLOBAL – SE VOCÊ VÊ ISSO, ESTE PROJETO ESTÁ SENDO USADO
        </div>

        {children}
      </body>
    </html>
  );
}
